# Generated by Django 2.1.3 on 2018-11-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='extra',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(),
        ),
    ]
