# Generated by Django 2.1.3 on 2018-11-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181124_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('activation_date', models.DateField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Package')),
            ],
        ),
    ]
