# Generated by Django 2.1.3 on 2018-11-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='eemployee',
            new_name='employee',
        ),
    ]
