# Generated by Django 2.1.3 on 2018-11-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20181124_2347'),
        ('employee', '0005_bonus'),
    ]

    operations = [
    ]
