# Generated by Django 2.1.3 on 2018-11-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_grantleave_payment_target_workedhours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendence',
            new_name='Attendance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='target',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workedhours',
            name='employee',
        ),
        migrations.RenameField(
            model_name='bonus',
            old_name='activation_date',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number_secondary',
        ),
        migrations.RemoveField(
            model_name='grantleave',
            name='date',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='jhondoe@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='grantleave',
            name='cause',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='grantleave',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grantleave',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='grantleave',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='n_id',
            field=models.CharField(default=11111, max_length=50),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='WorkedHours',
        ),
    ]
