# Generated by Django 2.1.3 on 2018-12-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_advance_payment_target_workedhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='package',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='package',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.RemoveField(
            model_name='grantleave',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='target',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workedhours',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Advance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='GrantLeave',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='WorkedHours',
        ),
    ]
