# Generated by Django 2.1.3 on 2018-12-04 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20181204_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payhead',
            old_name='calculation_unit',
            new_name='calculation_period',
        ),
        migrations.AddField(
            model_name='payhead',
            name='add_or_deduct',
            field=models.CharField(choices=[('add', 'add'), ('deduct', 'deduct')], default='add', max_length=10),
        ),
        migrations.AddField(
            model_name='payhead',
            name='attendence_production_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.ProductionAttendenceType'),
        ),
    ]
