# Generated by Django 2.1.3 on 2018-12-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20181204_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhead',
            name='attendence_production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.ProductionAttendenceType'),
        ),
    ]
