# Generated by Django 2.1.4 on 2018-12-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_auto_20181207_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_till_date', models.DateField()),
                ('rule', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('pay_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.PayHead')),
            ],
        ),
    ]
