# Generated by Django 2.1.4 on 2018-12-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_computationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_till_date', models.DateField()),
                ('first_unit', models.IntegerField()),
                ('value', models.FloatField()),
                ('second_unit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
