# Generated by Django 2.1.3 on 2018-12-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20181207_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
