# Generated by Django 2.1.3 on 2018-12-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computationinfo',
            name='pay_head',
        ),
        migrations.DeleteModel(
            name='UnitRelation',
        ),
        migrations.AddField(
            model_name='payhead',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='ComputationInfo',
        ),
    ]
