# Generated by Django 2.1.3 on 2018-12-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computationinfo',
            name='pay_head',
        ),
        migrations.DeleteModel(
            name='UnitRelation',
        ),
        migrations.DeleteModel(
            name='ComputationInfo',
        ),
    ]
