# Generated by Django 2.1.3 on 2018-12-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20181210_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAttendanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('Production', 'Production'), ('attendance/leave with pay', 'attendance/leave with pay'), ('attendance/leave without pay', 'attendance/leave without pay')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='production_attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.ProductionAttendanceType'),
        ),
        migrations.AlterField(
            model_name='payhead',
            name='attendence_production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.ProductionAttendanceType'),
        ),
        migrations.DeleteModel(
            name='ProductionAttendenceType',
        ),
    ]
